services:
  web:
    build: .
    ports:
      - "80:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=unemployment
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
